#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Verify LLVM IR generated by the Aurora compiler.
.DESCRIPTION
  Compiles each .aura example into a .ll file, then runs opt -passes=verify.
  Usage: pwsh scripts/test_ir_verify.ps1 [-Compiler <path>] [-ExamplesDir <path>]
#>
param(
    [string]$Compiler = "",
    [string]$ExamplesDir = "",
    [string]$OptPath = ""
)

$Root = Split-Path -Parent $PSScriptRoot
$IsWinOS = $env:OS -eq "Windows_NT"
if (-not $Compiler) { $Compiler = Join-Path $Root (Join-Path $(if ($IsWinOS) { "build/Release" } else { "build" }) $(if ($IsWinOS) { "aurorac.exe" } else { "aurorac" })) }
if (-not $ExamplesDir) { $ExamplesDir = Join-Path $Root "examples" }
if (-not $OptPath) { $OptPath = if ($IsWinOS) { "opt.exe" } else { "opt" } }

if (-not (Test-Path $Compiler)) {
    Write-Host "ERROR: Compiler not found at $Compiler" -ForegroundColor Red
    exit 1
}
if (-not (Test-Path $OptPath)) {
    $found = Get-Command "opt" -ErrorAction SilentlyContinue
    if (-not $found) { $found = Get-Command "opt.exe" -ErrorAction SilentlyContinue }
    if ($found) { $OptPath = $found.Source }
}
if (-not (Test-Path $OptPath)) {
    Write-Host "ERROR: opt not found at $OptPath" -ForegroundColor Red
    exit 1
}

Write-Host "=== LLVM IR Verification Pipeline ===" -ForegroundColor Cyan

$examples = Get-ChildItem -Recurse -Path $ExamplesDir -Filter "*.aura" |
    Where-Object { $_.FullName -notmatch 'node_modules|packages|dist' } |
    Where-Object { $_.Directory.Name -ne '2d' } |
    Where-Object { $_.Directory.Name -ne 'mobile' }

Write-Host "Found $($examples.Count) .aura examples"

$passed = 0
$failed = 0
$failures = @()

$tmpDir = Join-Path $Root "output\ir_verify_tmp"
if (Test-Path $tmpDir) { Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue }
New-Item -ItemType Directory -Path $tmpDir -Force | Out-Null

foreach ($file in $examples) {
    $rel = $file.FullName.Substring($Root.Length + 1)

    # Compile to a temp output dir (one-per-file to avoid collisions)
    $outDir = Join-Path $tmpDir $file.Name
    Remove-Item -Recurse -Force $outDir -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null

    Write-Host -NoNewline "."
    $output = & $Compiler $file.FullName 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failed++
        $errLine = ($output | Select-String -Pattern "\[Error\]" | Select-Object -First 1)
        if (-not $errLine) { $errLine = $output | Select-Object -Last 1 }
        $failures += "$rel => COMPILE ERROR: $errLine"
        continue
    }

    # The compiler always writes to output/ir/ from CWD, so capture from there
    $irFiles = @()
    $cwdIrDir = Join-Path $Root "output\ir"
    if (Test-Path $cwdIrDir) {
        $irFiles = Get-ChildItem -Path $cwdIrDir -Filter "*.ll"
        # Move them to our tmp dir and clean up
        foreach ($ir in $irFiles) {
            $dest = Join-Path $outDir $ir.Name
            Move-Item -Path $ir.FullName -Destination $dest -Force
        }
        Remove-Item -Recurse -Force $cwdIrDir -ErrorAction SilentlyContinue
    }

    if ($irFiles.Count -eq 0) {
        $failed++
        $failures += "$rel => no .ll file generated"
        continue
    }

    $allOk = $true
    $nullDev = if ($IsWinOS) { "nul" } else { "/dev/null" }
    foreach ($irFile in Get-ChildItem -Path $outDir -Filter "*.ll") {
        $verifyOutput = & $OptPath -passes=verify -o $nullDev $irFile.FullName 2>&1
        if ($LASTEXITCODE -ne 0) {
            $allOk = $false
            $errMsg = ($verifyOutput | Out-String).Trim()
            $failures += "$rel ($($irFile.Name)) => IR VERIFY FAILED: $errMsg"
        }
    }

    if ($allOk) { $passed++ } else { $failed++ }
}

# Cleanup
Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue

Write-Host ""
Write-Host ""
Write-Host "=== Results ===" -ForegroundColor Cyan
Write-Host "Passed: $passed"
Write-Host "Failed: $failed"

if ($failures.Count -gt 0) {
    Write-Host ""
    Write-Host "Failures:" -ForegroundColor Red
    foreach ($f in $failures) {
        Write-Host "  $f" -ForegroundColor Red
    }
    exit 1
}

Write-Host "All IR files pass LLVM verification!" -ForegroundColor Green
exit 0
